### ISSUE TITLE
Doesn't seem to be working with Sql Express

### ISSUE THREAD

**Issue by Chesheersky** [dyatchenko/ServiceBrokerListener#1]
Currently I'm trying to use this solution on two DBs. The first one is MS SQL Standard and another is Express. The solution works with Standard version like a charm, but seems to be not compatible with Express version, since I receive no notifications at all.
Am I doing something wrong, or it is supposed to work that way?

**Comment by dyatchenko** [comment]
Definetly, it supposed to work ok. Sql Express supports service broker. Did you try to start unit tests on Sql Express DB? User must have permissions described below:

 GRANT CREATE PROCEDURE TO [TempUser];
 GRANT CREATE SERVICE TO [TempUser];
 GRANT CREATE QUEUE  TO [TempUser];
 GRANT REFERENCES ON CONTRACT::[DEFAULT] TO [TempUser]
 GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [TempUser];
 GRANT CONTROL ON SCHEMA::[temp] TO [TempUser]; -- if schema isn't specified you should use dbo

Are there any exceptions or error codes?

**Comment by dyatchenko** [comment]
Ok. I think I found root of problem. According to this answer http://stackoverflow.com/a/6959922/2013969 you should start script ALTER AUTHORIZATION ON DATABASE::[<dbname>] TO [sa].
I will add this function inside SqlDependencyEx within couple of hours. Thanks!

**Comment by Chesheersky** [comment]
Thank you for such a quick reply =) I will try both of your advices tomorrow.

**Comment by dyatchenko** [comment]
Thank you too for this issue! I'll try to fix it before tomorrow.

**Comment by Chesheersky** [comment]
Have tried the latest version. Looks like my problem wasn't fixed. I receive no updates in my app, although all the tests for another database on the same DB-server are green. There should be some difference between them. I'll try to find it out.

**Comment by Chesheersky** [comment]
A solution to the issue is found. There were two problems basically.   

The first one: According to [this](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx) `SqlConnection.ConnectionString` doesn't normally expose password of user. This fact has made `TsqlHelper.GetSqlDependencyEx` method a bit tricky. One can not simply use this extension method and Sql Server Authentication at the same time. Probably it would be better to remove the method, but it is up to you.  

The second one: It is not enough to grant user CONTROL on a database. It is also necessary to grant it on a server, otherwise it seems not to be working.  

I'm closing the issue, since it is possible to fix the problem without changes in the code.

**Comment by dyatchenko** [comment]
Ok. You are right. I'll remove it. Grant CONTROL SERVER permission is necessary in case of unconfigured service broker. Component checks Service Broker configuration in the beginnging, tryes configure and throws exceprtion if permissions are unsufficient. If service broker has already been configured it is not neccessary to have server control permissions. I wrote two permission tests about it in the last commit.

**Comment by Chesheersky** [comment]
Glad to be useful, besides I have personal interests ;)
