### ISSUE TITLE
Multiple subscription

### ISSUE THREAD

**Issue by onbrokenwings** [dyatchenko/ServiceBrokerListener#10]
I have already checked out the library itself and it works like a charm on SQL Server Express 2014, with obviously the fact of enabling the Service Broker feature on the target database which I initially missed, but I have the express necessity to track updates on multiple tables. How can I manage them? What I have seen is like Service Broker only supports to track your initial subscription until you ask yourself for an immediate rollback. Any help would be appreciated. Thank you.

**Comment by dyatchenko** [comment]
Hi,

Thanks for the issue. Only thing you need to do is to create another instance of the `SqlDependencyEx` class with different identity (1 - by default). e.g.:

    var anotherTableListener = new SqlDependencyEx(connStr, "FooDB", "AnotherFooTable", identity: 2);
    anotherTableListener.Start();

Thanks.

**Comment by sp00n5** [comment]
I am just starting testing and have it set up to monitor 10 tables currently.  Nice and easy to set up.

**Comment by dyatchenko** [comment]
Thanks!

**Comment by onbrokenwings** [comment]
I have already tested the possibility to add consequent instances attached to different tables and it definitely works. FYI two details in order to make the whole thing happen (SQLServer side):

    ALTER DATABASE dbTest SET ENABLE_BROKER ;
    ALTER AUTHORIZATION ON DATABASE::dbTest TO userTest

Thank you so much for the comments.

**Comment by dyatchenko** [comment]
Thanks for the information!
