### ISSUE TITLE
ActiveEntities list memory leak into concurrent multithread context

### ISSUE THREAD

**Issue by GrgDmr** [dyatchenko/ServiceBrokerListener#11]
Hi @dyatchenko 

First of all this library is great !! :)

I am to use your library in a multithreaded environment. During performance optimization I came across a problem that seems to belong to the type of memory leaks. Using the diagnostic tool of visual studio I am to have this situation (after causing an intense dependency from sql server db):

![image](https://cloud.githubusercontent.com/assets/10920712/12417255/0090ac84-bea7-11e5-849e-b01cb4c512fd.png)

in the picture the application is in waiting mode. As you can see there is a reference to the List <int> of ActiveEntities. 

Inserting using ConcurrentDictionary(.net 4.0) it appears that the behavior has improved and the reference is no longer present. 

This is the list of the changes I've made to the code:

1. (line 437)
from 
```
private static readonly List<int> ActiveEntities = new List<int>(); 
```
to 
```
private static readonly ConcurrentDictionary<int, byte> ActiveEntities = new ConcurrentDictionary<int, byte>();
```

2. (line 525)
from  
```
lock (ActiveEntities)
            {
                if (ActiveEntities.Contains(this.Identity))
                    throw new InvalidOperationException("An object with the same identity has already been started.");
                ActiveEntities.Add(this.Identity);
            }
```
to 
```
ActiveEntities.TryAdd(this.Identity, byte.MinValue);
```

3. (line 570)
from 
```
lock (ActiveEntities)
                if (ActiveEntities.Contains(Identity)) ActiveEntities.Remove(Identity);
```
to             
```
byte itemRemoved;
            ActiveEntities.TryRemove(Identity, out itemRemoved);
```

that's all

**Comment by dyatchenko** [comment]
Hi, thanks for the issue.

I'm afraid, but throwing an exception in case of start a `SqlDependencyEx` instance with an identity which was used before for another `SqlDependencyEx` instance is important. You shouldn't start two instances of `SqlDependencyEx` with the same identity for the same database.

It looks like you don't solve your memory leak problem by using the concurrent dictionary. The `ActiveEntities` list shows the number of `SqlDependencyEx` instances which **were started** but **were not stopped**. That means that you have about 15000 unique listeners working, which means that you have about 15000 triggers in your database even though you got rid of the `ActiveEntities` list.

As I mentioned in [this](https://github.com/dyatchenko/ServiceBrokerListener/issues/12) ticket it is important to avoid using many listeners for the same purpose. The best practice here will be using a **single** `SqlDependencyEx` instance and then share received changes with whatever method you want. 

Thanks,
Dmitrii
