### ISSUE TITLE
Does Identity need to be unique to database?

### ISSUE THREAD

**Issue by sessio** [dyatchenko/ServiceBrokerListener#12]
If in a client i use ``SqlDependencyEx`` to monitor multiple tables, and then have multiple instances of that client on different computers using the same database - do i need to make sure that the ``Identity`` parameter of the ``SqlDependencyEx`` constructor is unique in the database context, or just for application instance?

I.e. Is it a problem if two programs track changes in the same database, and use the same ``Identity`` numbers?

**Comment by dyatchenko** [comment]
Hi, thanks for the issue.

Yes, that's a problem if two programs use the same ID. An ID should be used *per instance*.
That's the best solution we found yet. There was an algorithm which allowed using multiple instances of `SqlDependencyEx` without any ID's, but it caused conversation endpoints leaks and we decided to get rid of it.
`SqlDependencyEx` uses a trigger *per instance* which means if you have many `SqlDependencyEx` instances you will get many triggers on your table. Also, I would recommend avoid using the client-server logic on the database side. The best practice here will be using an instance of `SqlDependencyEx` inside a service which shares changes with many clients.

Thanks

**Comment by sessio** [comment]
Ok, thanks for the response and architecture tip. A dedicated service seems like a cleaner approach, and would help get rid of the uncatched exceptions caused by `stop()` on application close..

**Comment by dyatchenko** [comment]
The exception appears in the parallel thread and it is expected behavior when you stop the instance. Thus, it shouldn't impact your app much. However, it is not the first time when people pointing me out on it and I just added an empty catch to the background thread, so you it won't bother you anymore.

Regards,
Dmitrii

**Comment by sessio** [comment]
Oh ok thanks :+1:
