### ISSUE TITLE
deployment may fail but broker actually works.

### ISSUE THREAD

**Issue by dominusbelial** [dyatchenko/ServiceBrokerListener#13]
i had no issues with the code on my local computer but the following exception was thrown on the production server: Current user doesn''t have CONTROL SERVER permission to enable service broker. Grant sufficient permissions to current user or execute ALTER DATABASE [<dbname>] SET ENABLE_BROKER with admin rights. 
sql server installation adds by default CONTROL SERVER permissions to user installing the database service, but this is actually not required to enable the broker service, ENABLE_BROKER will run just fine without CONTROL SERVER permissions on some configurations. so i had to do this... 

`private const string SQL_FORMAT_INSTALL_SEVICE_BROKER_NOTIFICATION = @
                -- Setup Service Broker
                IF EXISTS (SELECT * FROM sys.databases 
                                    WHERE name = {0} AND (is_broker_enabled = 0 )) 
                BEGIN
                     ALTER DATABASE [{0}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
                        ALTER DATABASE [{0}] SET ENABLE_BROKER; 
                        ALTER DATABASE [{0}] SET MULTI_USER WITH ROLLBACK IMMEDIATE
                END
                -- Create a queue which will hold the tracked information 
                IF NOT EXISTS (SELECT * FROM sys.service_queues WHERE name = {1})
                    CREATE QUEUE {3}.[{1}]
                -- Create a service on which tracked information will be sent 
                IF NOT EXISTS(SELECT * FROM sys.services WHERE name = {2})
                    CREATE SERVICE [{2}] ON QUEUE {3}.[{1}] ([DEFAULT]) 
            ";`

**Comment by dyatchenko** [comment]
Hi, thanks for the issue.

Yes, as I mentioned in the [How To Use](https://github.com/dyatchenko/ServiceBrokerListener/blob/master/README.md) article you should turn Service Broker on before you start using `SqlDependencyEx`.

Thant's a great remark that you don't probably need the CONTROL SERVER permissions to start Service Broker. I will check it up and write a couple of tests.

Thank you very much!
Dmitrii

**Comment by dominusbelial** [comment]
this article may shed some light on the issue, perhaps the smarterasp guys (the hosting service i'm using) are following some of these patterns to allow "baby admins" do their job.

http://www.jasonstrate.com/2013/05/security-questions-difference-between-sysadmin-and-control-server-permission/

**Comment by WhiteKarma** [comment]
Hello all, 

@dominusbelial, your code overcomes the problem of permissions that i had on my hosting service also, but if i may add just a slight detail to your format string, the names of the database, the service and the queue should be in quotes.  
This component solved my problem, the notifications are fast and reliable as never. Thank you very much @dyatchenko for the nice piece of code!!!

All the best.

**Comment by VitaliySHTIRBU** [comment]
Every time when I change a SQL QUERY in c# I have to update it in SQL because it will  use the old stored procedure, or just to remove it from  SQL and it will create a new one for me.

Overall the code is great,  Highly recommend to use it instead of Sqldependency .
Thanks a lot **@dyatchenko**

**Comment by dyatchenko** [comment]
The issue was fixed (permission checks were removed)

**Comment by stamhaney** [comment]
Thanks @dyatchenko for the code. Can you tell me how can I monitor Alter Table and Drop Table notification with this ?
