### ISSUE TITLE
Xml parse error

### ISSUE THREAD

**Issue by sessio** [dyatchenko/ServiceBrokerListener#14]
`XElement.Parse` throws an XmlException if it encounters invalid charactes in the `notificationMessage` string [here](https://github.com/dyatchenko/ServiceBrokerListener/blob/65070b12a2597496ed94c74aa3427580271340be/ServiceBrokerListener/ServiceBrokerListener.Domain/SqlDependencyEx.cs#L36-L44)

I encountered this on a table that had a `char` column that contained a null character.

Patched my local copy by wrapping the `Parse` in a try-catch and discarding results on error since I don't really need it.

Exception message:
`Additional information: '.', hexadecimal value 0x00, is an invalid character.`

**Comment by dyatchenko** [comment]
I removed checking for restricted XML symbols when the string is parsed. That issue shouldn't happen again. You also should be careful when working with an XML which contains invalid characters though - it will throw an exception when you try call myXml.ToString().
