### ISSUE TITLE
Sqldependencyex not working after datatable update

### ISSUE THREAD

**Issue by mahesh428** [dyatchenko/ServiceBrokerListener#15]
Hi ,
I am using signalr to push notifications to user .Whenever any changes in table happens i am pushing notifications to frontend.But the sqldependencyex is not firing the onchange event.Please let me know if i made any mistakes.

            using (SqlDependencyEx sqlDependency =  new SqlDependencyEx(ConfigurationManager.ConnectionStrings["dbConnectionstring"].ConnectionString, "EIS_BMT", "EIS_Notifications"))
            {
                
                
                sqlDependency.TableChanged += dependency_OnChange;
                // Make table changes.
                sqlDependency.Start();

                // Wait a little bit to receive all changes.
                Thread.Sleep(1000);

                IHubContext context = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
                return context.Clients.All.RecieveNotification(totalNewMessages, Messages);
            }

  private void dependency_OnChange(object sender, SqlDependencyEx.TableChangedEventArgs e)
        {
            NotificationHub nhub = new NotificationHub();
            nhub.SendNotifications();
        }

**Comment by dyatchenko** [comment]
You dispose a SqlDependencyEx entity before you get some notifications (The USING statement does that). In your case you have to create a static field with SqlDependencyEx and start it once when your app is started and stop it when your app is stopped.

**Comment by dyatchenko** [comment]
Write a console app wich gets notifiactions first to ensure that everything is configured fine and then transfer it to the webapp.

**Comment by mahesh428** [comment]
Yes.You are correct.I have implemented using static connection and it is working fine.

I have one more issue --some times i am getting following issue. May i know the reason for it.

 if (ActiveEntities.Contains(this.Identity))
                    throw new InvalidOperationException("An object with the same identity has already been started.");


Thanks 
Mahesh.

**Comment by dyatchenko** [comment]
Check the readme file please. That clause is used to prevent creating many SqlDependencyEx entities with the same identity. You should use different inentity **for each instance**. That algorithm is used to implement correct disposal of the resources.

**Comment by dyatchenko** [comment]
If the component works as expected, could you please remove your comment for this answer on stackoverflow: http://stackoverflow.com/a/29786963/2013969
