### ISSUE TITLE
Reserved names causes SQL_FORMAT_CREATE_INSTALLATION_PROCEDURE to fail

### ISSUE THREAD

**Issue by smillerk2** [dyatchenko/ServiceBrokerListener#18]
I have a table called dbo.Order but this appears to cause problems during the set up.

```
SET @select = STUFF((SELECT '','' + COLUMN_NAME
						                        FROM INFORMATION_SCHEMA.COLUMNS
						                        WHERE TABLE_NAME = ''{5}'' AND TABLE_CATALOG = ''{0}''
						                        FOR XML PATH ('''')
						                        ), 1, 1, '''')
```
I believe that square brackets are required around {5}.

**Comment by dyatchenko** [comment]
Hi,

Thanks for the issue. It looks like you should use [dbo].[Order] when you pass the table name as the parameter.

Thanks,
Dmitrii

**Comment by dyatchenko** [comment]
I don't confirm that issue. Just wrote a unit test which uses the following:

    using (var sqlDependencyFirstTable = new SqlDependencyEx(
           TEST_CONNECTION_STRING,
           "TestDatabase",
           "Order",
           "temp",
           SqlDependencyEx.NotificationTypes.Insert,
           true,
           0))

And got the following result:

![image](https://cloud.githubusercontent.com/assets/10171967/15523536/07b5a370-21d0-11e6-96d5-4006069ae8c0.png)

There is shouldn't be any problems.

Thanks,
Dmitrii

**Comment by dyatchenko** [comment]
In the code you provided the table name is used as a string - it shouldn't cause any problems there.

**Comment by smillerk2** [comment]
Hi,

Thanks for looking so quickly. I appear to have been mistaken and "assumed" the issue was my Order table. However, it looks like it might be a different table that contains a column called "Order" and I think this is breaking the trigger definition.

**Comment by smillerk2** [comment]
The "Order" column was breaking the installation. I had to change the code to the following in order to set up the listener:

```
SET @select = STUFF((SELECT '','' + ''['' + COLUMN_NAME + '']''
						                        FROM INFORMATION_SCHEMA.COLUMNS
						                        WHERE TABLE_NAME = ''{5}'' AND TABLE_CATALOG = ''{0}''
						                        FOR XML PATH ('''')
						                        ), 1, 1, '''')
```

**Comment by dyatchenko** [comment]
Thanks for the remark!
It was fixed and a unit test was written:

![image](https://cloud.githubusercontent.com/assets/10171967/16847755/6aa552d8-49a7-11e6-8df7-410854344274.png)

Thanks,
Dmitrii
