### ISSUE TITLE
When not receiving details issue with XML format

### ISSUE THREAD

**Issue by WhiteKarma** [dyatchenko/ServiceBrokerListener#20]
Hello, 

I had a problem turning off the XML details only on production server on the hosting service for which i do not have much control. I got a malformed XML exception with the default XML message:

`SET @message = N'<root/>'`

So the shorter valid message i could send on the trigger was this one:

`SET @message = N'<root><inserted><row></row></inserted><deleted><row></row></deleted></root>'`

Great component, very well done, thank you very much!!!

**Comment by dyatchenko** [comment]
Hi @WhiteKarma,

I wrote a unit test for that case and haven't found any exceptions:

![image](https://cloud.githubusercontent.com/assets/10171967/16849349/df16a340-49ae-11e6-8e90-7436c8d3614c.png)

It looks like you get an exception in external code outside the component. 
If so, it might be not an issue for the component. 
If we turn the details off that means we don't transfer *any* text between the server and the client.
For the component it meant to be "None" notification status and `e.Data.Elements().Count() == 0`

Thanks,
Dmitrii
