### ISSUE TITLE
SqlDependencyEx.Stop method causes problems in load balanced environment

### ISSUE THREAD

**Issue by smillerk2** [dyatchenko/ServiceBrokerListener#21]
Is it possible for a flag to be passed into the Stop method that is used to control the UninstallNotification logic? The reason being is that, in a clustered environment, if Stop is invoked from Server 1 then the SQL listeners are dropped and this causes Server 2 to start failing. Ideally it would be possible to control whether the objects get dropped.

**Comment by dyatchenko** [comment]
The answer is here: #29.

**Comment by dyatchenko** [comment]
#29
