### ISSUE TITLE
Error on Installation script procedure (tr_Listener_1 failed)

### ISSUE THREAD

**Issue by Adwelean** [dyatchenko/ServiceBrokerListener#24]
Hi,

I have a little problem when I try to start the listener on SQL Server 2012, when i try to execute `[sp_InstallListenerNotification_1]` 

I have this error :

```
Msg 156, Niveau 15, État 1, Procédure tr_Listener_1, Ligne 21
Syntaxe incorrecte vers le mot clé 'Not'.
```

You can try :

```sql
USE [MyDatabase]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[sp_InstallListenerNotification_1]

SELECT	'Return Value' = @return_value

GO
```

DEBUG :
```c#
private void InstallNotification()
        {
            string execInstallationProcedureScript = string.Format(
                SQL_FORMAT_EXECUTE_PROCEDURE,
                this.DatabaseName,
                this.InstallListenerProcedureName,
                this.SchemaName);
            ExecuteNonQuery(GetInstallNotificationProcedureScript(), this.ConnectionString); **#OK**
            ExecuteNonQuery(GetUninstallNotificationProcedureScript(), this.ConnectionString); **#OK**
            ExecuteNonQuery(execInstallationProcedureScript, this.ConnectionString); **#FAILED**
        }
```

Are you an idea ?
Adw.

**Comment by Adwelean** [comment]
I'm solve my problem

Workaround (Replace set @select in SQL_FORMAT_CREATE_INSTALLATION_PROCEDURE):
```sql
SET @select = STUFF((SELECT '', LTRIM(['''' + COLUMN_NAME + '''']) AS '' + QUOTENAME(REPLACE(COLUMN_NAME, '' '', ''''))
						                         FROM INFORMATION_SCHEMA.COLUMNS
						                         WHERE TABLE_NAME = ''{5}'' AND TABLE_CATALOG = ''{0}''
						                         FOR XML PATH ('''')
						                         ), 1, 1, '''')
```

**Comment by dyatchenko** [comment]
Hi @Adwelean,

Thanks for the issue.
It looks like it is related to this one: #18

Thanks,
Dmitrii

**Comment by dyatchenko** [comment]
Hi @Adwelean,

As far as I understood your table has a column which has spaces. Having spaces in node names is illegal for XML. Thus, we have to escape illegal characters from the column name before creating XML output.
But it looks like there is no build-in function in MSSQL which escapes a string to make a valid XML node name and that issue cannot be fixed for now. 

The best we can do here is to recommend using simple XML-valid column names.

Thanks,
Dmitrii
