### ISSUE TITLE
Error at opening database SqlConnection

### ISSUE THREAD

**Issue by Narf92** [dyatchenko/ServiceBrokerListener#27]
Hello, I have been working with sqldependencyEx for a time in a Console Application and now I have to port it in a Windows Service. While debugging in Windows Service, throws me an exception that's an error of logging into the database. In the console Application I didn't get this problem and I copied the files from that project.

This is the error message that displays me:

> An exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll but was not handled in user code
Additional information: No se puede abrir la base de datos "LINX" solicitada por el inicio de sesión. Error de inicio de sesión.
Error de inicio de sesión del usuario 'NT AUTHORITY\SYSTEM'.*

*I added after the last line because I didn't see it.

I'm using windows authentication in Microsoft Sql Server 2014, so I don't have user and password, any clue about this error? I'm working with sql express if it helps.

**Comment by dyatchenko** [comment]
Hi @narf92,

Thanks for the issue. It looks like the service is started on behalf of NT AUTHORITY\SYSTEM which doesn't have enough permissions to run some queries. You should grant appropriate permissions to that user or create a service login (with login and pass) and use it for SQLDependencyEx.

Thanks,
Dmitrii

**Comment by Narf92** [comment]
@dyatchenko I solved the problem creating another user with all grants. Thanks for helping!

**Comment by dyatchenko** [comment]
You are weclome! Let me know if you faced with some issues.
