### ISSUE TITLE
Hi, I tried multiple listeners as you propose in the readme.  It appears that only the second listener ever are running. I confirmed behavior when i switched listener 1 with listener 2

### ISSUE THREAD

**Issue by daddio** [dyatchenko/ServiceBrokerListener#28]

**Comment by cdfell** [comment]
Multiple listeners works quite well for us but we implement one set of
triggers, queues, etc. per table we listen for changes to. When we need
more than one listener for a table we utilized GoF Observer pattern, and
that has really worked out extremely well. If you are interested have a
look here http://www.dofactory.com/net/observer-design-pattern.

Best regards to you and your project.

**Comment by daddio** [comment]
Thanks for your quick reply.

First I want to inform you that I really like what you have done here!! Great work.

I think you did not understand what i mean. Let me try and explain more.
I do not want multiple listeners for one table, but rather one listener for more than one table.

More like the way you describe usage for multiple tables.
var listener1 = new SqlDependencyEx(connectionString, "YourDatabase", "YourTable1", identity: 1);
var listener2 = new SqlDependencyEx(connectionString, "YourDatabase", "YourTable2", identity: 2);
in our solution i can see both triggers, queues and services do get created but only the second ever catch the changes and i cannot work out why.


I did try to use SqlDependency class before but it is not doing what i expected and i came across this solution which does exactly what we need.

Please help.

Regards

**Comment by cdfell** [comment]
You are welcome but all I am is an enduser, same as you, of dayacthenko's
excellent application. We have both scenarios in use, (a) multiple
listeners listening for changes on multiple different tables, and (b) have
multiple listeners (by way of observer pattern) listening to changes on one
table. I understand you need scenario (a) and all I can offer is that we
have multiple instances of SqlDependencyEx, each hosted by a separate
windows service. This of course requires separate queues, service brokers,
triggers, etc. to make work.

Hope that helps!

**Comment by dyatchenko** [comment]
Hi @daddio,

Thanks for the issue. There is a special unit test for your case and it works fine - take a look in the project.

![image](https://cloud.githubusercontent.com/assets/10171967/17422355/00df1d78-5a66-11e6-95e1-6ba49c29dfbe.png)

We might miss something. Which SQL Server do you use? Are you sure that you use different identities? Are you able to start the unit test described above?

Thanks,
Dmitrii

**Comment by dyatchenko** [comment]
If there is no comments it should be closed.
