### ISSUE TITLE
"Data?" that breaks the compiler in SqlDependencyEx.cs

### ISSUE THREAD

**Issue by gabigeo** [dyatchenko/ServiceBrokerListener#30]
Hi,

In SqlDependencyEx.cs at lines 53, 54, and 57 there is a strange notation "Data?" that breaks the compiler.

return Data?.Element(INSERTED_TAG) != null
                               ? Data?.Element(DELETED_TAG) != null
                                     ? NotificationTypes.Update
                                     : NotificationTypes.Insert
                               : Data?.Element(DELETED_TAG) != null
                                     ? NotificationTypes.Delete
                                     : NotificationTypes.None;

I guess this is a typo.

**Comment by dyatchenko** [comment]
Hi @gabigeo,

Thanks for the issue, but it is not a typo. It is [Null-conditional operator][1] which appeared in [C# 6.0][2]
We may rewrite this code for C# 5.0 or older.

Thanks,
Dmitrii

   [1]: https://msdn.microsoft.com/en-us/library/dn986595(v=vs.140).aspx
   [2]: https://msdn.microsoft.com/en-us/library/ms228593.aspx

**Comment by gabigeo** [comment]
Thanks for clarification. I should upgrade also :)
