### ISSUE TITLE
Problem with case-sensitive mssql server (express)

### ISSUE THREAD

**Issue by Pinguwien** [dyatchenko/ServiceBrokerListener#31]
Hi there. Great plugin so far :-) Works like a charm right now, thank you!

I just had some struggle because in our environment, for some reason the SQL Server is set to look for matching case in SQL statements. (more info here: http://stackoverflow.com/questions/3296428/changing-sql-server-collation-to-case-insensitive-from-case-sensitive - but please don't ask me why! i don't know either and for 99% of time i'm happy to let other people deal with the sql machine itself, but I needed the event broker mechanism ;) ) 

So now the "Issue" is a very minor one. But it has cost me a few hours to find out. So...:

You are using `sp_executeSql` in your `SQL_FORMAT_CREATE_INSTALLATION_PROCEDURE` which made the created procedure fail "inside the sql-server" here. So I'd suggest you just change it to `sp_executesql` which worked out to be the solution for me. I'd do it myself, but no time at the moment ;)

**Comment by dyatchenko** [comment]
Hi @Pinguwien,

Thanks for founding it! That's a good improvement!

Thanks,
Dmitrii
