### ISSUE TITLE
Problem getting notifications from changes not directly done on SQL Server Studio

### ISSUE THREAD

**Issue by HolgerBD** [dyatchenko/ServiceBrokerListener#51]
I have implemented the SqlDependencyEx class in windows service on windows 10. It works fine, as long as I make those changes in SQL Server Studio. When I do the changes with a program, on the same database I get no notification.
The Service is not on the same node as the database.
As the user in the service and the Program making the changes are different it might be a problem with access rights.

Any hints?

**Comment by dyatchenko** [comment]
Hello,

You can try running both under admin rights and if it works then reduce
permissions. Otherwise, you can try running unit tests in the solution and
check if any of them fail.

Thanks,
Dmitrii

**Comment by HolgerBD** [comment]
It seems, we solvedthe Problem. The user who makes rhe Changes must have the possibility to fire the events. We gabe the user the Same right that are nessecary to implement the service in sql server and it looks as if it works.

Thank to Dimitij for the help and special thanks for the software

Holger
