### ISSUE TITLE
ASP.NET example?

### ISSUE THREAD

**Issue by dotnetshadow** [dyatchenko/ServiceBrokerListener#7]
Hi great library,

Does this work in an asp.net environment?

This is an example of how the Microsoft one works in ASP.NET environment
http://venkatbaggu.com/signalr-database-update-notifications-asp-net-mvc-usiing-sql-dependency/

Do you have an equivalent example?

**Comment by cjones26** [comment]
+1 on this, I have tried this in a ASP.NET environment and am so far unable to get it working properly.

**Comment by cjones26** [comment]
FYI--I have a very small ASP.NET WebAPI 2.2/SignalR 2.2/Angular application which simply needed to refresh on any DB changes and was able to implement it like so (I'm not the best coder so if anyone can chime in on any issues with this methodology):

```C#
protected void Application_Start()
{
    GlobalConfiguration.Configure(WebApiConfig.Register);
    _dependency.NotificationProcessStopped += _dependency_NotificationProcessStopped;
    _dependency.TableChanged += dependency_TableChanged;
    _dependency.Start();
}

private void _dependency_NotificationProcessStopped(object sender, EventArgs e)
{
    _dependency.Stop();
    _dependency.Start();
}

protected void Application_Shutdown()
{
    _dependency.Stop();
}

private void dependency_TableChanged(object sender, SqlDependencyEx.TableChangedEventArgs e)
{
    HostsHub.SendMessages();
}
```

This works perfectly for my use case.
